apiVersion: v1
kind: Service
metadata:
  name: credit-scoring-api
  labels:
    app: credit-scoring-api
spec:
  type: ClusterIP
  selector:
    app: credit-scoring-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
